In [2]:
import numpy as np
# Generates the problem
A = np.array()
y = np.array([0, 1, 0])

# Solve the system
x_sol = np.linalg.solve(A, y)
print(f"The solution is {x_sol}.")

The solution is [ 1. -1.  0.].


In [4]:
#Define a test problem
A = np.array([[1, 1, 1], [2, 1, 2], [0, 0, 1]])
print(A)

x_true = np.array([1, 0, 1]) 
y = A @ x_true #calculate the y

x_sol = np.linalg.solve(A, y)
print(x_sol)



[[1 1 1]
 [2 1 2]
 [0 0 1]]
[1. 0. 1.]


In [8]:
print(f"Relative error  = {np.linalg.norm(x_sol - x_true)/ np.linalg.norm(x_true)}")

Relative error  = 0.0


In [9]:
print(f"K(A) = {np.linalg.cond(A,2)} ")

K(A) = 9.412293755407312 


In [27]:
#Exercise
n = 1000
# Define a matrix A which is a randome matrix with normal entries of dimension n x n. 
# Define a vector x_true of length n and all ones.
# Deine a vector y such that x_true is the solution of y = A x(_true) ( test problem)

In [28]:
A = np.random.randn(n,n)
x_true = np.ones((n,1))
y = A @ x_true


In [29]:
import scipy


In [30]:
#compute the LU factorization of A by the  lu  function in scipy
P, L, U = scipy.linalg.lu(A)
print(L)

[[ 1.          0.          0.         ...  0.          0.
   0.        ]
 [-0.81436754  1.          0.         ...  0.          0.
   0.        ]
 [-0.17372487  0.13555654  1.         ...  0.          0.
   0.        ]
 ...
 [-0.26131912  0.24421132 -0.23736591 ...  1.          0.
   0.        ]
 [-0.00940661 -0.22988124  0.14808356 ...  0.30483004  1.
   0.        ]
 [-0.41653579  0.37739565 -0.44411613 ...  0.65852256  0.48484735
   1.        ]]


In [34]:
for n in [3,5,10,20]:
    A = np.random.randn(n,n)
    x_true = np.ones((n,1))
    y = A @ x_true


    #compute the LU factorization of A by the  lu  function in scipy
    P, L, U = scipy.linalg.lu(A)


    #Compute PT y(PT = P Transpose)
    PTy = P.T @ y

    #Solve Forward- Backward substitution
    z=scipy.linalg.solve_triangular(L,PTy,lower=True)
    x=scipy.linalg.solve_triangular(U,z, lower=False)
    #z=np.linalg.solve(L,PTy)
    #x=np.linalg.solve(U,z)
    #Comoute error 
    E = np.linalg.norm(x - x_true) / np.linalg.norm(x_true)
    print(f"{n} -> Error:{E}.")
    print(f"{n} -> K(A) = {np.linalg.cond(A,2)} ")
    print(x)



#For n = 3,5,10,20 -> print out error and the condition number of A

3 -> Error:3.4518236613818645e-16.
3 -> K(A) = 40.80455853970989 
[[1.]
 [1.]
 [1.]]
5 -> Error:1.4043333874306804e-16.
5 -> K(A) = 12.59379085257721 
[[1.]
 [1.]
 [1.]
 [1.]
 [1.]]
10 -> Error:3.614624287906422e-16.
10 -> K(A) = 43.41730729847926 
[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]
20 -> Error:1.3401086353509591e-15.
20 -> K(A) = 27.705547343592368 
[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]


In [33]:
print(x)

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]
